# Generated by Django 6.0.1 on 2026-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor ($)')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=100, verbose_name='Subcategoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observação')),
            ],
        ),
    ]
