# Generated by Django 6.0.1 on 2026-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='info',
            field=models.TextField(blank=True, verbose_name='Informações Extras'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número / Documento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='origem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origem / Fornecedor'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)'),
        ),
    ]
