# Generated by Django 6.0.1 on 2026-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_despesa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('lazer', 'Lazer'), ('transporte', 'Transporte')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info Extras'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='origem',
            field=models.CharField(choices=[('mercado', 'Mercado'), ('feira', 'Feira'), ('outro', 'Outro')], max_length=100, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='subcategoria',
            field=models.CharField(max_length=100, verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)'),
        ),
    ]
